AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS App Stack: ALB, Auto Scaling Group, and Launch Template."

Parameters:
  ProjectName:
    Type: String
    Default: MyWebArchitecture
    Description: Must match the ProjectName used in other stacks.

  # 自動取得最新的 Amazon Linux 2023 AMI ID
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64"
  
  #加入SSL憑證
  CertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:534207971056:certificate/a93ab9b7-1021-45ff-8c5e-89f162d803c2
    Description: "The ARN of the SSL certificate in AWS ACM"
    
  DBUser:
    Type: String
    Default: admin
  DBPassword:
    Type: String
    Default: dbpassword
    NoEcho: true
  DBName:
    Type: String
    Default: myappdb

Resources:
  # ==========================================
  # 1. Application Load Balancer (Public)
  # ==========================================
  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-ALB
      Scheme: internet-facing
      Type: application
      Subnets:
        - Fn::ImportValue: !Sub ${ProjectName}-PublicSubnet1
        - Fn::ImportValue: !Sub ${ProjectName}-PublicSubnet2
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ProjectName}-ALBSG
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-ALB

  # ==========================================
  # 2. Target Group
  # ==========================================
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-TG
      Port: 80
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-VPCID
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      TargetType: instance

  # ==========================================
  # 3. ALB Listener (HTTP)
  # ==========================================
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: "HTTPS"
            Port: "443"
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: "HTTP_301"
  # ==========================================
  # 4. ALB Listener (HTTPS) -> 負責解密並轉發
  # ==========================================
  ALBListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
  # ==========================================
  # 5. Launch Template (EC2 設定檔)
  # ==========================================
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${ProjectName}-LaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: t2.micro

        # 綁定 IAM Instance Profile
        IamInstanceProfile:
          Name:
            Fn::ImportValue: !Sub ${ProjectName}-InstanceProfile

        # 綁定 Security Group
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${ProjectName}-AppSG

        UserData:
          Fn::Base64: !Sub
            - |
              #!/bin/bash
              # 1. 安裝環境
              dnf update -y
              dnf install -y nginx python3-pip unzip

              # 2. 準備後端程式碼 (從您原本的私有 Data Bucket 下載)
              # 假設您將後端程式碼打包成 backend.zip 上傳到私有 Bucket
              aws s3 cp s3://${S3BucketName}/backend.zip /home/ec2-user/backend.zip
              unzip /home/ec2-user/backend.zip -d /home/ec2-user/api_app

              # 3. 安裝 Python 套件
              cd /home/ec2-user/api_app/backend

              cat <<EOF > .env
              DB_HOST=${RDSEndpoint}
              DB_USER=${DBUser}
              DB_PASSWORD=${DBPassword}
              DB_NAME=${DBName}
              DB_PORT=3306
              AWS_REGION="ap-southeast-2"
              COGNITO_USER_POOL_ID="ap-southeast-2_TCtE1x780"
              COGNITO_APP_CLIENT_ID="3e01cbi503u29lb0jpm62ospm4"
              COGNITO_DOMAIN="ap-southeast-2tcte1x780.auth.ap-southeast-2.amazoncognito.com"
              COGNITO_REDIRECT_URI=https://www.yueyue.site/auth/callback/
              COGNITO_CLIENT_SECRET="1v5aaact530l7cdve24shfm1qsseckbr03a3067i8ggk2usretml"
              ALLOWED_EMAIL_DOMAIN="g.ncu.edu.tw"
              
              S3_BUCKET_NAME=${S3BucketName}
              EOF

              pip3 install -r requirements.txt

              # 4. 設定 Systemd 讓 FastAPI 開機自動執行
              cat <<EOF > /etc/systemd/system/fastapi.service
              [Unit]
              Description=FastAPI Backend
              After=network.target

              [Service]
              User=root
              WorkingDirectory=/home/ec2-user/api_app/backend
              # 讓 Uvicorn 跑在 8000 port
              ExecStart=/usr/bin/python3 -m uvicorn src.main:app --host 0.0.0.0 --port 8000
              Restart=always

              [Install]
              WantedBy=multi-user.target
              EOF

              # 5. 設定 Nginx 反向代理 (Port 80 -> 8000)
              # 這樣 ALB (Port 80) 的流量就會轉給 FastAPI
              cat <<EOF > /etc/nginx/conf.d/default.conf
              server {
                  listen 80;
                  server_name _;

                  location / {
                      proxy_pass http://127.0.0.1:8000;
                      proxy_set_header Host \$host;
                      proxy_set_header X-Real-IP \$remote_addr;
                      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  }
              }
              EOF

              # 6. 啟動服務
              systemctl daemon-reload
              systemctl start fastapi
              systemctl enable fastapi
              systemctl start nginx
              systemctl enable nginx

            - S3BucketName:
                Fn::ImportValue: !Sub ${ProjectName}-S3BucketName
              RDSEndpoint:
                Fn::ImportValue: !Sub ${ProjectName}-RDSEndpoint
  # ==========================================
  # 6. Auto Scaling Group
  # ==========================================
  MyASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${ProjectName}-ASG
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      # 設定在 Private Subnets
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub ${ProjectName}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${ProjectName}-PrivateSubnet2
      TargetGroupARNs:
        - !Ref MyTargetGroup
      MinSize: "2"
      MaxSize: "4"
      DesiredCapacity: "2"
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

# ==========================================
# Outputs
# ==========================================
Outputs:
  LoadBalancerDNS:
    Description: The public DNS name of the load balancer
    Value: !GetAtt MyALB.DNSName
    Export:
      Name: !Sub ${ProjectName}-ALB-DNS
